run:
  timeout: 3m

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow
      - unnamedResult
      - unnecessaryBlock
      - unnecessaryDefer
    settings:
      rangeValCopy:
        sizeThreshold: 512
      hugeParam:
        sizeThreshold: 512
  gocyclo:
    min-complexity: 16
  golint:
    min-confidence: 0
  govet:
    check-shadowing: false
  lll:
    line-length: 300
  misspell:
    locale: US

issues:
  exclude-rules:
    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters: [bodyclose, gocritic, gosec, staticcheck, stylecheck]

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - execinquery
    - exhaustive
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unparam
