port: 9443
certDir: "./hack/certs"
healthAddr: ":8080"
metricsAddr: ":8081"
rules:
  - name: 'docker.io rewrite rule'
    # image refs must match at least one of the rules, and not match any excludes
    matches:
      - '^docker.io'
    excludes:
      # for example, exclude ubuntu from harbor's proxy cache
      - '^docker.io/(library/)?ubuntu:.*$'
    replace: 'harbor.example.com/dockerhub-proxy'
    checkUpstream: false
  - name: 'docker.io ubuntu rewrite rule'
    # image refs must match at least one of the rules, and not match any excludes
    matches:
      - '^docker.io/(library/)?ubuntu:.*$'
    replace: 'harbor-v2.awscmhqa2.k8s.indeed.tech/dockerhub-proxy-auth'
    checkUpstream: true # tests if the manifest for the rewritten image exists
    authSecretName: "harborv2-qa"
  - name: 'docker.io rewrite rule with imagePullSecret change'
    # image refs must match at least one of the rules, and not match any excludes
    matches:
      - '^docker.io'
    replace: 'harbor.example.com/dockerhub-proxy'
    authSecretName: "harborv2-qa"
    replaceImagePullSecrets: true
