// Code generated by mockery. DO NOT EDIT.

package dynamic

import mock "github.com/stretchr/testify/mock"

// mockProjectsCache is an autogenerated mock type for the ProjectsCache type
type mockProjectsCache struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *mockProjectsCache) List() []projectWithSummary {
	ret := _m.Called()

	var r0 []projectWithSummary
	if rf, ok := ret.Get(0).(func() []projectWithSummary); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]projectWithSummary)
		}
	}

	return r0
}

// Ready provides a mock function with given fields:
func (_m *mockProjectsCache) Ready() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
