kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "harbor-container-webhook.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "harbor-container-webhook.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harbor-container-webhook.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harbor-container-webhook.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---